// Code generated by "stringer -type nodeKind"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[number-0]
	_ = x[str-1]
	_ = x[ident-2]
	_ = x[binop-3]
}

const _nodeKind_name = "numberstridentbinop"

var _nodeKind_index = [...]uint8{0, 6, 9, 14, 19}

func (i nodeKind) String() string {
	if i < 0 || i >= nodeKind(len(_nodeKind_index)-1) {
		return "nodeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _nodeKind_name[_nodeKind_index[i]:_nodeKind_index[i+1]]
}
