// Code generated by "stringer -type tokenKind"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[noneToken-0]
	_ = x[intToken-1]
	_ = x[stringToken-2]
	_ = x[opToken-3]
	_ = x[identToken-4]
}

const _tokenKind_name = "noneTokenintTokenstringTokenopTokenidentToken"

var _tokenKind_index = [...]uint8{0, 9, 17, 28, 35, 45}

func (i tokenKind) String() string {
	if i < 0 || i >= tokenKind(len(_tokenKind_index)-1) {
		return "tokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenKind_name[_tokenKind_index[i]:_tokenKind_index[i+1]]
}
